version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: billpayment
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      WALLET_ENV: dev
      DB_URL: jdbc:postgresql://postgres:5432/billpayment
      DB_USER: postgres
      DB_PASSWORD: root
      JWT_SECRET: secret
      JWT_EXPIRATION_MS: 500000000
    depends_on:
      - postgres
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
